### PR TITLE
Disable check hyphens flag

### PR DESCRIPTION
**Pull request by Sebmaster**

### CODE REVIEW

**Comment by domenic** [comment]
I've updated this to run the new tests in https://github.com/w3c/web-platform-tests/pull/5976 and am getting four failures where it should be throwing an exception but doesn't:

```
      1) ‍.example (CheckJoiners is true)
      2) xn--1ug.example
      3) يa (CheckBidi is true)
      4) xn--a-yoc
```

Any ideas, @Sebmaster @rmisev?

**Comment by Sebmaster** [comment]
Checkjoiners is probably a bug, checkbidi has never been implemented. Gotta dig into why the other two should fail/do not.

**Comment by rmisev** [comment]
(1) actually is "\u200D.example"
(2) is the "\u200D.example" in Punycode
(4) is the "يa" in Punycode
So (2) and (4) must return an error the same as (1) and (3).
To pass tests the `CheckJoiners` and `CheckBidi` must be set to `true` (unfortunately, not implemented in the Sebmaster/tr46.js).

**Comment by domenic** [comment]
Hmm OK. I wonder if we can get that implemented soon, or if we should just sign-off on the spec changes as we've tested them as best we can.

**Comment by Sebmaster** [comment]
Ah, CheckJoiners enables ContextJ rules, that's also never been implemented.

**Pull request closed without merging**
