### PR TITLE
'@' not supported in path

### PR DESCRIPTION
**Pull request by chriscantu**
As I understand the spec (my understanding can be incorrect), the path should support @.  

I am referencing the 3rd step in the path state:  
https://url.spec.whatwg.org/#path-state which should support the URL Code Points.  https://url.spec.whatwg.org/#url-code-points

I tried adding a fix but my url parsing & state machine 'foos' are very weak. =)

### CODE REVIEW

**Comment by Sebmaster** [comment]
Pretty sure it should support @ in the path, but your test case is in the wrong format, you need to add a second space after the url for it to test correctly.

**Comment by chriscantu** [comment]
@Sebmaster Thank you for the helpful feedback.  The test now works.  I ran into this issue on zombieJS which may be running an older version of whatwg-url. Sounds like we can close this one.

**Comment by Sebmaster** [comment]
Merged the test as a43a6e0473167c340fefe273d127ecd5a0eaa7ff.

**Comment by chriscantu** [comment]
:+1:

**Pull request closed without merging**
